### ISSUE TITLE
Externalize config directory as it is different between oc cluster up, mininishift

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/cloud-native-infra#17]
Externalize  config directory as it is different between `oc cluster  up`, `mininishift`, ....

By example, the jenkins role uses a hard coded reference which is different from the directory used by minishift or oc cluster up

```
- name: Set config file
  set_fact:
    config_file: /etc/origin/master/master-config.yaml

- name: Update configuration file
  shell: |
    echo "jenkinsPipelineConfig:" >> {{ config_file }}
    echo "  autoProvisionEnabled: false" >> {{ config_file }}
```
