### ISSUE TITLE
Refactor post_installation playbook to use new convention -> import|include_roles

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/cloud-native-infra#18]
Since Ansible 2.4, we can adopt this new convention as we can : 
- Define the task to be used from the role and then have one role to by example, install, uninstall
- Pass condition

- Old
```
---
- hosts: webservers
  roles:
    - { role: foo, tags: ["bar", "baz"] }
```

- New
```
---
- hosts: webservers
  tasks:
  - import_role:
      name: foo
    tags:
    - bar
    - baz
```
