### ISSUE TITLE
Add a var to specify how many volumes should be created

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/cloud-native-infra#42]
Currently, the pv and temp created are default to `3`

```
volume:
  defaults: #define the defaults for all Persistent Volumes
      storage: 5Gi
      persistentVolumeReclaimPolicy: Recycle

volumes:
    pv001:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv002:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
    pv003:
      storage: "{{ volume.defaults.storage }}"
      persistentVolumeReclaimPolicy: "{{ volume.defaults.persistentVolumeReclaimPolicy }}"
```

I suggest to add a var in order to let to override the value and remove the hard coded list as defined under `volumes` and use instead a dynamic list generated
